# Generated by Django 4.2.5 on 2023-10-02 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_challenge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='featured_video',
        ),
        migrations.CreateModel(
            name='what_you_learn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.CharField(max_length=500)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.challenge')),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.CharField(max_length=500)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.challenge')),
            ],
        ),
    ]
