# Generated by Django 4.2.5 on 2023-11-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_challenge_featured_video_what_you_learn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=130)),
                ('repoUrl', models.URLField(blank=True, max_length=130)),
                ('liveUrl', models.URLField(blank=True, max_length=130)),
                ('feedback', models.TextField(blank=True, max_length=130)),
            ],
        ),
    ]
