# Generated by Django 4.2.5 on 2023-11-23 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_submitform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitform',
            name='feedback',
            field=models.TextField(max_length=130),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='liveUrl',
            field=models.URLField(max_length=130),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='repoUrl',
            field=models.URLField(max_length=130),
        ),
    ]
