# Generated by Django 4.2.5 on 2023-11-23 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_submitform_feedback_alter_submitform_liveurl_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubmitForm',
        ),
    ]
