# Generated by Django 4.2.5 on 2023-11-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_delete_submitform'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=130)),
                ('repoUrl', models.URLField(max_length=130)),
                ('liveUrl', models.URLField(max_length=130)),
                ('feedback', models.TextField(max_length=130)),
            ],
        ),
    ]
