# Generated by Django 4.2.5 on 2023-11-24 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_submitform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='featured_image',
        ),
    ]
