# Generated by Django 4.2.5 on 2023-11-24 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_challenge_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='category',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='challenge',
        ),
        migrations.DeleteModel(
            name='SubmitForm',
        ),
        migrations.RemoveField(
            model_name='what_you_learn',
            name='challenge',
        ),
        migrations.DeleteModel(
            name='Challenge',
        ),
        migrations.DeleteModel(
            name='Requirement',
        ),
        migrations.DeleteModel(
            name='what_you_learn',
        ),
    ]
