# Generated by Django 4.2.5 on 2023-11-29 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_challenge_submitform_what_you_learn_requirement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='challenge',
        ),
        migrations.RemoveField(
            model_name='what_you_learn',
            name='challenge',
        ),
        migrations.DeleteModel(
            name='Challenge',
        ),
        migrations.DeleteModel(
            name='Requirement',
        ),
        migrations.DeleteModel(
            name='what_you_learn',
        ),
    ]
